name: AI PR Review

on:
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: install AI Review Library
        run: pip install minimal_pr_review_agent

      - name: Agent Code Review
        run: python -c "from minimal_pr_review_agent.llm_pr_review import main; main()"
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}